name: sd2022_m1_env
channels:
  - conda-forge
  - defaults
dependencies:
  - appnope=0.1.3
  - asttokens=2.4.1
  - backcall=0.2.0
  - bzip2=1.0.8
  - ca-certificates=2023.11.17
  - comm=0.1.4
  - debugpy=1.8.0
  - decorator=5.1.1
  - exceptiongroup=1.2.0
  - executing=2.0.1
  - importlib-metadata=7.0.1
  - importlib_metadata=7.0.1
  - ipykernel=6.28.0
  - ipython=8.12.0
  - jedi=0.19.1
  - jupyter_client=8.6.0
  - jupyter_core=4.12.0
  - libexpat=2.5.0
  - libffi=3.4.2
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libzlib=1.2.13
  - matplotlib-inline=0.1.6
  - ncurses=6.4
  - nest-asyncio=1.5.8
  - openssl=3.2.0
  - packaging=23.2
  - parso=0.8.3
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.3.2
  - platformdirs=4.1.0
  - prompt-toolkit=3.0.42
  - prompt_toolkit=3.0.42
  - psutil=5.9.7
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pygments=2.17.2
  - python=3.9.18
  - python-dateutil=2.8.2
  - python_abi=3.9
  - pyzmq=25.1.2
  - readline=8.2
  - setuptools=68.2.2
  - six=1.16.0
  - stack_data=0.6.2
  - tk=8.6.13
  - tornado=6.3.3
  - traitlets=5.14.0
  - typing_extensions=4.9.0
  - wcwidth=0.2.12
  - wheel=0.42.0
  - xz=5.2.6
  - zeromq=4.3.5
  - zipp=3.17.0
  - pip:
      - contourpy==1.2.0
      - cycler==0.12.1
      - fonttools==4.47.0
      - importlib-resources==6.1.1
      - joblib==1.3.2
      - kiwisolver==1.4.5
      - matplotlib==3.8.2
      - numpy==1.26.2
      - pandas==2.1.4
      - pillow==10.1.0
      - pyparsing==3.1.1
      - pytz==2023.3.post1
      - scikit-learn==1.3.2
      - scipy==1.11.4
      - seaborn==0.13.0
      - tabulate==0.9.0
      - threadpoolctl==3.2.0
      - tzdata==2023.3
